export const queryKeys = {
  stats: ['admin', 'stats'],
  businesses: (status) => ['admin', 'businesses', status || 'all'],
  businessDetail: (id) => ['admin', 'business', id],
  users: (role) => ['admin', 'users', role || 'all'],
  userDetail: (id) => ['admin', 'user', id],
  products: ['admin', 'products'],
  productDetail: (sku) => ['admin', 'product', sku],
  orders: (filters) => ['admin', 'orders', filters],
  orderDetail: (id) => ['admin', 'order', id],
  orderRequests: (status) => ['admin', 'order-requests', status || 'all'],
  pendingDisbursements: ['admin', 'payments', 'pending'],
  payTransactions: ['admin', 'payments', 'transactions'],
  disbursements: ['admin', 'payments', 'disbursements'],
  platformSettings: ['admin', 'platform-settings'],
  fxRates: ['admin', 'fx-rates'],
  categories: ['admin', 'categories'],
  promotions: ['admin', 'promotions'],
  coupons: ['admin', 'coupons'],
  auditLogs: ['admin', 'audit-logs'],
  notifications: ['admin', 'notifications'],
  snapAskCases: (filters) => ['admin', 'snap-ask', 'cases', filters],
  snapAskCase: (id) => ['admin', 'snap-ask', 'case', id],
  snapAskMessages: (id) => ['admin', 'snap-ask', 'messages', id],
};
